export const CITIZEN_ADDED= "CITIZEN_ADDED";
export const CITIZEN_COVID_STATUS_CHANGED= "CITIZEN_COVID_STATUS_CHANGED";
export const UPDATE_LIST= "UPDATE_LIST";
export const FILTER_COUNTRY= "FILTER_COUNTRY";
export const CHANGE_THEME= "CHANGE_THEME";
// export const SIGN_UP= "SIGN_UP";
